POST http://localhost:3000/register
Content-Type: application/json

{
  "full_name": "eswar",
  "email_address": "eswarvinayvenkatesh26@gmail.com",
  "password": "mysecretpassword",
  "address": "123 Main Street, Cityville, State",
  "phone_number": "555-123-4567",
  "gender": "Male"
}


###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email_address": "eswarvinayvenkatesh26@gmail.com",
  "password": "1234567"
}

###

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9hZGRyZXNzIjoiZXN3YXJ2aW5heXZlbmthdGVzaDI2QGdtYWlsLmNvbSIsImlhdCI6MTY5MDg4ODUzMX0.d-PrL-NR6RbD6MrAC8ctpwboIPe5BlJlxwgPAt2Rz7Y

###

PUT http://localhost:3000/updateprofile/17/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9hZGRyZXNzIjoiZXN3YXJ2aW5heXZlbmthdGVzaDI2QGdtYWlsLmNvbSIsImlhdCI6MTY5MDg4ODM5MH0.4v--rp28lKcC2Zx_QFsVUKRgSxbu9oMOsotNBW_E39k
Content-Type: application/json

{
  
    "full_name": "e2swar",
    "email_address": "eswarvinayvenkatesh26@gmail.com",
    "address": "123 Main Street, Cityville, State",
    "phone_number": "555-123-4567",
    "password":"1234567",
    "gender": "Male"

}



//ADMIN CALLS
###

GET http://localhost:3000/users

###
GET http://localhost:3000/user/14/

###
DELETE http://localhost:3000/deleteuser/13/

###
POST http://localhost:3000/adduser
Content-Type: application/json

{
  
  "username": "joh33444n",
  "name": "Johnweeeeeerteerty Doe",
  "password": "sec3ureer",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}

###
PUT http://localhost:3000/updateuser/41/
Content-Type: application/json

{
  
  "username": "joh33444n",
  "name": "Johnweeeeeerteerty Doe",
  "password": "sec3ureer",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}

###

DELETE http://localhost:3000/deleteAllUsers