POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "eswar123",
  "email": "eswarvinayvenkatesh26@gmail.com",
  "name": "eswar",
  "password": "eswar365",
  "gender": "Male",
  "location": "Bengaluru"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "venkatesh123",
  "password": "venkatesh123"
}

###

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbmthdGVzaDEyMyIsImlhdCI6MTY5MDQ1OTkzNn0.paSWtgc96ylbqzSgAMEkKHqZA72YxeQMM9BysBGaAmY

###

PUT http://localhost:3000/updateprofile/46/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbmthdGVzaDEyMyIsImlhdCI6MTY5MDQ1OTkzNn0.paSWtgc96ylbqzSgAMEkKHqZA72YxeQMM9BysBGaAmY
Content-Type: application/json

{
  
  "username": "123456",
  "name": "Johnweeeeeerteerty Doe",
  "password": "123456",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}


//ADMIN CALLS
###

GET http://localhost:3000/users

###
GET http://localhost:3000/user/46/

###
DELETE http://localhost:3000/deleteuser/28/

###
POST http://localhost:3000/adduser
Content-Type: application/json

{
  
  "username": "joh33444n",
  "name": "Johnweeeeeerteerty Doe",
  "password": "sec3ureer",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}

###
PUT http://localhost:3000/updateuser/41/
Content-Type: application/json

{
  
  "username": "joh33444n",
  "name": "Johnweeeeeerteerty Doe",
  "password": "sec3ureer",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}

###

DELETE http://localhost:3000/deleteAllUsers