POST http://localhost:3000/register
Content-Type: application/json

{
  "full_name": "eswar",
  "email_address": "eswarvinayvenaktesh26@gmail.com",
  "password": "mysecretpassword",
  "address": "123 Main Street, Cityville, State",
  "phone_number": "555-123-4567",
  "gender": "Male"
}


###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email_address": "eswarvinayvenaktesh26@gmail.com",
  "password": "mysecretpassword"
}

###

GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbF9hZGRyZXNzIjoiZXN3YXJ2aW5heXZlbmFrdGVzaDI2QGdtYWlsLmNvbSIsImlhdCI6MTY5MDgwNjkzOH0.65L_d0fMkn8NJtcmd4sU2QYy_q8eBryj8ioCcPIFwkA

###

PUT http://localhost:3000/updateprofile/46/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbmthdGVzaDEyMyIsImlhdCI6MTY5MDQ1OTkzNn0.paSWtgc96ylbqzSgAMEkKHqZA72YxeQMM9BysBGaAmY
Content-Type: application/json

{
  
  "username": "123456",
  "name": "Johnweeeeeerteerty Doe",
  "password": "123456",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}


//ADMIN CALLS
###

GET http://localhost:3000/users

###
GET http://localhost:3000/user/20/

###
DELETE http://localhost:3000/deleteuser/28/

###
POST http://localhost:3000/adduser
Content-Type: application/json

{
  
  "username": "joh33444n",
  "name": "Johnweeeeeerteerty Doe",
  "password": "sec3ureer",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}

###
PUT http://localhost:3000/updateuser/41/
Content-Type: application/json

{
  
  "username": "joh33444n",
  "name": "Johnweeeeeerteerty Doe",
  "password": "sec3ureer",
  "gender": "Matyu",
  "location": "New rYeeeeeeeeetyuor2k, UrSA"

}

###

DELETE http://localhost:3000/deleteAllUsers